---
title: "Portfolio Optimization with Domain Knowledge"
author: "Mustafa M. Ali"
subtitle: 'Dec. 18, 2025'
execute:
  eval: false
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
sansfont: Georgia
mainfont: Georgia
format: pdf
---

\vspace{0.25cm}

```{r, warning=FALSE, error=FALSE}
#install.packages("quantmod")
library(quantmod)
library(tidyverse)
library(patchwork)
library(ggridges)
library(tidymodels)
library(ggrepel)
library(readr)
theme_set(theme_bw())

companies_df <- read_csv("Data/sp500_companies.csv") |> na.omit()
index_df <- read_csv("Data/sp500_index.csv") |> na.omit()
stocks_df <- read_csv("Data/sp500_stocks.csv") |> na.omit()

companies_df
index_df
stocks_df |> distinct(Symbol) |> arrange(Symbol)
```


```{r}

names(companies_df[c(-15)])

similarity_df <- data.frame()

for (row1 in 1:nrow(companies_df)){
  for (row2 in 1:nrow(companies_df)){
    if (companies_df[row1, "Symbol"] != companies_df[row2, "Symbol"]) {
      if (companies_df[row1, "Sector"] == companies_df[row2, "Sector"] & companies_df[row1, "Industry"] == companies_df[row2, "Industry"]) {
        similarity_df <- similarity_df |> rbind(data.frame(Ticker1 = companies_df[row1, "Symbol"], Ticker2 = companies_df[row2, "Symbol"], EconSimilarity = 0.7))
      } else if (companies_df[row1, "Sector"] == companies_df[row2, "Sector"]) { # industries are different, but sectors are the same
        similarity_df <- similarity_df |> rbind(data.frame(Ticker1 = companies_df[row1, "Symbol"], Ticker2 = companies_df[row2, "Symbol"], EconSimilarity = 0.3))
      }
    }
  }
}
similarity_df <- similarity_df |> rename(Ticker1=Symbol, Ticker2=Symbol.1)
similarity_df
```



```{r}
#Problematic tickers: 200, 252, 399, 431, 436
tickers <- unique(companies_df$Symbol[-c(200, 252, 399, 431, 436)])
tickers
getQuote(tickers, what = yahooQF(c("Symbol", "Previous Close", "52-week Low", "52-week High", "50-day Moving Average", "200-day Moving Average", "Market Capitalization", "P/E Ratio", "Price/Book")))
```







